### ISSUE TITLE
Hacktoberfest 

### ISSUE THREAD

**Issue by raylansoares** [raylansoares/vue-dynamic-form#2]
Esse é um projeto em VueJs que renderiza um formulário a partir de um json.

Tem alguma ideia legal para o projeto? Abre uma issue aqui!

**Comment by Aveesh52-zz** [comment]
Can i contribute to this issue?

**Comment by raylansoares** [comment]
> Can i contribute to this issue?

Yes, if you have a cool idea for the project feel free to open a issue or pull request!
